# Write CSV

In [2]:
import pandas as pd

dis = {"a":[1,2,3,4,5,6],"s":[1,2,3,4,5,6],"d":[1,2,3,4,5,6]}

d = pd.DataFrame(dis)

print(d)

d.to_csv("Test_new.csv")

   a  s  d
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
5  6  6  6

exel file already contain the row so, if we want to remove the index than use

In [3]:
import pandas as pd

dis = {"a":[1,2,3,4,5,6],"s":[1,2,3,4,5,6],"d":[1,2,3,4,5,6]}

d = pd.DataFrame(dis)

print(d)

d.to_csv("Test_new1.csv", index = False)

   a  s  d
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
5  6  6  6

# Read CSV Files in Python Pandas

In [2]:
import pandas as pd

csv_1 = pd.read_csv("//Users//princemaurya//Desktop//Jupyter//stock_data.csv")

csv_1

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,GKWLIMITED,GKW Limited,21375,711,30.049203
4,21STCENMGM,21st Century Management Services,110375,3879,28.450831
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613
6,UNIENTER,Uniphos Enterprises Limited,162601,7553,21.528002
7,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.801420
8,SKMEGGPROD,SKM Egg Products Export (India) Ltd,1541130,87775,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.938733
10,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.555297
11,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833
12,LINC,Linc Limited,60551,4076,14.853673
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.247963
16,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.641332
17,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.443312
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
22,ALKALI,Alkali Metals Limited,157496,19059,8.263315
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862

Now ab hm csv file ke andar koi bhi work/function perform kr skte hai

if we want to get any row then use nrows function

In [7]:
csv_2 = pd.read_csv("//Users//princemaurya//Desktop//Jupyter//stock_data.csv",nrows=3)

csv_2
# print(type(csv_2))

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450

if we want to get any column then use usecols function

In [9]:
csv_3 = pd.read_csv("//Users//princemaurya//Desktop//Jupyter//stock_data.csv",usecols=["SYMBOL","CHANGE"])

csv_3

        SYMBOL     CHANGE
0   ELECTTHERM  50.110003
1       NBIFIN  37.202586
2      HINDCON  32.953450
3   GKWLIMITED  30.049203
4   21STCENMGM  28.450831
5     ALPHAGEO  27.852613
6     UNIENTER  21.528002
7   JAGSNPHARM  17.801420
8   SKMEGGPROD  17.557733
9    SWELECTES  16.938733
10   NAHARPOLY  15.555297
11  PODDARHOUS  15.283833
12        LINC  14.853673
13  SHIVAMILLS  13.755541
14  PDMJEPAPER  12.823425
15        DSSL  11.247963
16    ANDREWYU  10.641332
17    LAXMICOT  10.443312
18        REPL  10.049914
19      PILITA  10.011751
20  BHAGYAPROP   9.987766
21    MUNJALAU   8.569318
22      ALKALI   8.263315
23   INTENTECH   7.607959
24    INDORAMA   7.606862

Also we can pass the index number of the column to get the column

In [10]:
csv_3 = pd.read_csv("//Users//princemaurya//Desktop//Jupyter//stock_data.csv",usecols=[0,3])

csv_3

        SYMBOL  AVG. VOLUME
0   ELECTTHERM         9457
1       NBIFIN          154
2      HINDCON         9248
3   GKWLIMITED          711
4   21STCENMGM         3879
5     ALPHAGEO         8356
6     UNIENTER         7553
7   JAGSNPHARM        73134
8   SKMEGGPROD        87775
9    SWELECTES        12276
10   NAHARPOLY        38574
11  PODDARHOUS         3012
12        LINC         4076
13  SHIVAMILLS        10391
14  PDMJEPAPER       102646
15        DSSL        23439
16    ANDREWYU       230048
17    LAXMICOT        19007
18        REPL        65700
19      PILITA       685602
20  BHAGYAPROP        30596
21    MUNJALAU        82307
22      ALKALI        19059
23   INTENTECH       164644
24    INDORAMA        89288

if we want to remove any row than use skiprows function

In [12]:
csv_3 = pd.read_csv("//Users//princemaurya//Desktop//Jupyter//stock_data.csv",skiprows=[0,3])

csv_3

,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.11000282
0,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
1,GKWLIMITED,GKW Limited,21375,711,30.049203
2,21STCENMGM,21st Century Management Services,110375,3879,28.450831
3,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613
4,UNIENTER,Uniphos Enterprises Limited,162601,7553,21.528002
5,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.801420
6,SKMEGGPROD,SKM Egg Products Export (India) Ltd,1541130,87775,17.557733
7,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.938733
8,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.555297
9,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833
10,LINC,Linc Limited,60551,4076,14.853673
11,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541
12,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.823425
13,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.247963
14,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.641332
15,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.443312
16,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049914
17,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.011751
18,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
19,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
20,ALKALI,Alkali Metals Limited,157496,19059,8.263315
21,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
22,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862

agar hme kisi particular column ko as a index use karna hai than use index_col functions

In [13]:
csv_3 = pd.read_csv("//Users//princemaurya//Desktop//Jupyter//stock_data.csv",index_col="SYMBOL")

csv_3

,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
SYMBOL,,,,
ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.110003
NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
GKWLIMITED,GKW Limited,21375,711,30.049203
21STCENMGM,21st Century Management Services,110375,3879,28.450831
ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613
UNIENTER,Uniphos Enterprises Limited,162601,7553,21.528002
JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.801420
SKMEGGPROD,SKM Egg Products Export (India) Ltd,1541130,87775,17.557733
SWELECTES,Swelect Energy Systems Limited,207954,12276,16.938733
NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.555297
PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833
LINC,Linc Limited,60551,4076,14.853673
SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541
PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.823425
DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.247963
ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.641332
LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.443312
REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049914
PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.011751
BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
ALKALI,Alkali Metals Limited,157496,19059,8.263315
INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862

Agar hme given row me se kisi ek ko header bnana hai than use header function

In [14]:
csv_3 = pd.read_csv("//Users//princemaurya//Desktop//Jupyter//stock_data.csv",header = 2)

csv_3

,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.20258621
0,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
1,GKWLIMITED,GKW Limited,21375,711,30.049203
2,21STCENMGM,21st Century Management Services,110375,3879,28.450831
3,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613
4,UNIENTER,Uniphos Enterprises Limited,162601,7553,21.528002
5,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.801420
6,SKMEGGPROD,SKM Egg Products Export (India) Ltd,1541130,87775,17.557733
7,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.938733
8,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.555297
9,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833
10,LINC,Linc Limited,60551,4076,14.853673
11,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541
12,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.823425
13,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.247963
14,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.641332
15,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.443312
16,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049914
17,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.011751
18,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
19,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
20,ALKALI,Alkali Metals Limited,157496,19059,8.263315
21,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
22,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862

agar hm name parameter ka use krte hai to hm heading ko bhi change kr skte hai

In [18]:
csv_3 = pd.read_csv("//Users//princemaurya//Desktop//Jupyter//stock_data.csv",names=["col1","col2","col3","col4","col5"])

csv_3

,col1,col2,col3,col4,col5
0,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
1,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.11000282
2,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.20258621
3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.95345023
4,GKWLIMITED,GKW Limited,21375,711,30.04920337
5,21STCENMGM,21st Century Management Services,110375,3879,28.45083129
6,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.85261268
7,UNIENTER,Uniphos Enterprises Limited,162601,7553,21.52800212
8,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.80141977
9,SKMEGGPROD,SKM Egg Products Export (India) Ltd,1541130,87775,17.55773284
10,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.93873284
11,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.55529728
12,PODDARHOUS,Poddar Housing and Development,46040,3012,15.28383313
13,LINC,Linc Limited,60551,4076,14.85367349
14,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.7555413
15,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.8234253
16,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.2479628
17,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.64133195
18,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.44331235
19,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.04991362
20,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.01175122
21,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987765618
22,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318028
23,ALKALI,Alkali Metals Limited,157496,19059,8.26331454
24,INTENTECH,Intense Technologies Limited,1252606,164644,7.607958577
25,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606861665

agar hm header ko hta ke new col dalna chahte hai then use header and prefix function

In [22]:
import pandas as pd

# Read CSV without header
csv_1 = pd.read_csv("/Users/princemaurya/Desktop/Jupyter/stock_data.csv", header=None)

# Assign column names manually with a prefix
csv_1.columns = [f"col{i}" for i in range(csv_1.shape[1])]

csv_1

,col0,col1,col2,col3,col4
0,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
1,ELECTTHERM,Electrotherm (India) Limited,473907,9457,50.11000282
2,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.20258621
3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.95345023
4,GKWLIMITED,GKW Limited,21375,711,30.04920337
5,21STCENMGM,21st Century Management Services,110375,3879,28.45083129
6,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.85261268
7,UNIENTER,Uniphos Enterprises Limited,162601,7553,21.52800212
8,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.80141977
9,SKMEGGPROD,SKM Egg Products Export (India) Ltd,1541130,87775,17.55773284
10,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.93873284
11,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.55529728
12,PODDARHOUS,Poddar Housing and Development,46040,3012,15.28383313
13,LINC,Linc Limited,60551,4076,14.85367349
14,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.7555413
15,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.8234253
16,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.2479628
17,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.64133195
18,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.44331235
19,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.04991362
20,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.01175122
21,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987765618
22,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318028
23,ALKALI,Alkali Metals Limited,157496,19059,8.26331454
24,INTENTECH,Intense Technologies Limited,1252606,164644,7.607958577
25,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606861665

agar hm integer type ke data ko float me covert krna chahte hai than use dtype parameter

In [23]:
csv_3 = pd.read_csv("//Users//princemaurya//Desktop//Jupyter//stock_data.csv",dtype={"TODAY - VOLUME":"float"})

csv_3

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,ELECTTHERM,Electrotherm (India) Limited,473907.0,9457,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754.0,154,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759.0,9248,32.953450
3,GKWLIMITED,GKW Limited,21375.0,711,30.049203
4,21STCENMGM,21st Century Management Services,110375.0,3879,28.450831
5,ALPHAGEO,Alphageo (India) Limited,232755.0,8356,27.852613
6,UNIENTER,Uniphos Enterprises Limited,162601.0,7553,21.528002
7,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892.0,73134,17.801420
8,SKMEGGPROD,SKM Egg Products Export (India) Ltd,1541130.0,87775,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954.0,12276,16.938733
10,NAHARPOLY,Nahar Poly Films Limited,600043.0,38574,15.555297
11,PODDARHOUS,Poddar Housing and Development,46040.0,3012,15.283833
12,LINC,Linc Limited,60551.0,4076,14.853673
13,SHIVAMILLS,Shiva Mills Limited,142943.0,10391,13.755541
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439,11.247963
16,ANDREWYU,Andrew Yule & Company Limited,2448026.0,230048,10.641332
17,LAXMICOT,Laxmi Cotspin Limited,198503.0,19007,10.443312
18,REPL,Rudrabhishek Enterprises Limited,660281.0,65700,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594.0,30596,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307,8.569318
22,ALKALI,Alkali Metals Limited,157496.0,19059,8.263315
23,INTENTECH,Intense Technologies Limited,1252606.0,164644,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288,7.606862